select ?url ?name ?lat ?lng ?s{

	?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://odp.jig.jp/odp/1.0#OpenDataCity>.

	?s <http://schema.org/url> ?url.

	?s <http://www.w3.org/2000/01/rdf-schema#label> ?name.

	?s <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?lat.

	?s <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?lng.

        ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://odp.jig.jp/odp/1.0#OpenDataCity>.

	filter(lang(?name) = "ja")

}
